# Generated by Django 2.1.2 on 2018-12-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUnit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='code')),
                ('parent_id', models.IntegerField(blank=True, null=True, verbose_name='parent id')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='name in English')),
                ('name_vn', models.CharField(blank=True, max_length=100, null=True, verbose_name='name in Vietnamese')),
                ('type', models.CharField(max_length=20, verbose_name='type')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='total')),
                ('vpromm', models.FloatField(blank=True, null=True, verbose_name='vpromm')),
            ],
            options={
                'verbose_name': 'administrative unit',
                'verbose_name_plural': 'administrative units',
            },
        ),
    ]
