# Generated by Django 2.2.2 on 2019-06-08 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0010_auto_20190607_1716'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbaresult',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cba_results', to='roads.Section'),
            preserve_default=False,
        ),
    ]
