# Generated by Django 2.2.2 on 2019-06-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cbaresult_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbaresult',
            name='esa_loading',
            field=models.FloatField(blank=True, null=True, verbose_name='esa loading'),
        ),
        migrations.AddField(
            model_name='cbaresult',
            name='truck_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='truck percent'),
        ),
        migrations.AddField(
            model_name='cbaresult',
            name='vehicle_utilization',
            field=models.FloatField(blank=True, null=True, verbose_name='vehicle utilization'),
        ),
    ]
