# Generated by Django 2.2.2 on 2019-06-10 14:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0001_initial'),
        ('core', '0003_auto_20190608_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('program', models.SmallIntegerField(blank=True, default=3, null=True, verbose_name='rolling program')),
                ('budget_percent', models.FloatField(blank=True, default=100.0, null=True, verbose_name='budget percentage')),
                ('total_capital', models.FloatField(blank=True, null=True, verbose_name='total capital cost')),
                ('periodic_maintenance_cost', models.FloatField(blank=True, null=True, verbose_name='period maintenance cost')),
                ('rehabilitation_financial_cost', models.FloatField(blank=True, null=True, verbose_name='Rehabilitation Financial Cost')),
                ('recurrent_cost', models.FloatField(blank=True, null=True, verbose_name='recurrent cost')),
                ('total_agency_cost', models.FloatField(blank=True, null=True, verbose_name='Total Capital Cost')),
                ('periodic_maintenance_road_works', models.FloatField(blank=True, null=True, verbose_name='Periodic Maintenance Road Works')),
                ('rehabilitation_road_works', models.FloatField(blank=True, null=True, verbose_name='Rehabilitation Road Works')),
                ('total_capital_road_works', models.FloatField(blank=True, null=True, verbose_name='Total Capital Road Works')),
                ('total_recurrent_road_works', models.FloatField(blank=True, null=True, verbose_name='Total Capital Road Works')),
                ('no_prioritised_sections', models.SmallIntegerField(blank=True, null=True, verbose_name='number of selected priority road sections')),
                ('npv', models.FloatField(blank=True, null=True, verbose_name='npv')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrations.AdminUnit')),
            ],
            options={
                'verbose_name': 'budget scenario',
            },
        ),
    ]
