# Generated by Django 2.2.2 on 2019-06-10 14:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0001_initial'),
        ('core', '0004_budgetscenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalFinancialCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('work_cost_y1', models.FloatField(blank=True, null=True, verbose_name='work cost year 1')),
                ('work_cost_y2', models.FloatField(blank=True, null=True, verbose_name='work cost year 2')),
                ('work_cost_y3', models.FloatField(blank=True, null=True, verbose_name='work cost year 3')),
                ('work_cost_y4', models.FloatField(blank=True, null=True, verbose_name='work cost year 4')),
                ('work_cost_y5', models.FloatField(blank=True, null=True, verbose_name='work cost year 5')),
                ('work_cost_y6', models.FloatField(blank=True, null=True, verbose_name='work cost year 6')),
                ('work_cost_y7', models.FloatField(blank=True, null=True, verbose_name='work cost year 7')),
                ('work_cost_y8', models.FloatField(blank=True, null=True, verbose_name='work cost year 8')),
                ('work_cost_y9', models.FloatField(blank=True, null=True, verbose_name='work cost year 9')),
                ('work_cost_y10', models.FloatField(blank=True, null=True, verbose_name='work cost year 10')),
                ('work_cost_y11', models.FloatField(blank=True, null=True, verbose_name='work cost year 11')),
                ('work_cost_y12', models.FloatField(blank=True, null=True, verbose_name='work cost year 12')),
                ('work_cost_y13', models.FloatField(blank=True, null=True, verbose_name='work cost year 13')),
                ('work_cost_y14', models.FloatField(blank=True, null=True, verbose_name='work cost year 14')),
                ('work_cost_y15', models.FloatField(blank=True, null=True, verbose_name='work cost year 15')),
                ('work_cost_y16', models.FloatField(blank=True, null=True, verbose_name='work cost year 16')),
                ('work_cost_y17', models.FloatField(blank=True, null=True, verbose_name='work cost year 17')),
                ('work_cost_y18', models.FloatField(blank=True, null=True, verbose_name='work cost year 18')),
                ('work_cost_y19', models.FloatField(blank=True, null=True, verbose_name='work cost year 19')),
                ('work_cost_y20', models.FloatField(blank=True, null=True, verbose_name='work cost year 20')),
                ('work_cost_total', models.FloatField(blank=True, null=True, verbose_name='work cost total')),
                ('npv_y1', models.FloatField(blank=True, null=True, verbose_name='npv year 1')),
                ('npv_y2', models.FloatField(blank=True, null=True, verbose_name='npv year 2')),
                ('npv_y3', models.FloatField(blank=True, null=True, verbose_name='npv year 3')),
                ('npv_y4', models.FloatField(blank=True, null=True, verbose_name='npv year 4')),
                ('npv_y5', models.FloatField(blank=True, null=True, verbose_name='npv year 5')),
                ('npv_y6', models.FloatField(blank=True, null=True, verbose_name='npv year 6')),
                ('npv_y7', models.FloatField(blank=True, null=True, verbose_name='npv year 7')),
                ('npv_y8', models.FloatField(blank=True, null=True, verbose_name='npv year 8')),
                ('npv_y9', models.FloatField(blank=True, null=True, verbose_name='npv year 9')),
                ('npv_y10', models.FloatField(blank=True, null=True, verbose_name='npv year 10')),
                ('npv_y11', models.FloatField(blank=True, null=True, verbose_name='npv year 11')),
                ('npv_y12', models.FloatField(blank=True, null=True, verbose_name='npv year 12')),
                ('npv_y13', models.FloatField(blank=True, null=True, verbose_name='npv year 13')),
                ('npv_y14', models.FloatField(blank=True, null=True, verbose_name='npv year 14')),
                ('npv_y15', models.FloatField(blank=True, null=True, verbose_name='npv year 15')),
                ('npv_y16', models.FloatField(blank=True, null=True, verbose_name='npv year 16')),
                ('npv_y17', models.FloatField(blank=True, null=True, verbose_name='npv year 17')),
                ('npv_y18', models.FloatField(blank=True, null=True, verbose_name='npv year 18')),
                ('npv_y19', models.FloatField(blank=True, null=True, verbose_name='npv year 19')),
                ('npv_y20', models.FloatField(blank=True, null=True, verbose_name='npv year 20')),
                ('npv_total', models.FloatField(blank=True, null=True, verbose_name='npv total')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrations.AdminUnit')),
            ],
            options={
                'verbose_name': 'Total Financial Cost',
            },
        ),
    ]
