# Generated by Django 2.1.4 on 2018-12-20 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0001_initial'),
        ('roads', '0002_auto_20181016_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('section_id',), 'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
        migrations.RemoveField(
            model_name='section',
            name='road_section_id',
        ),
        migrations.RemoveField(
            model_name='section',
            name='section_name',
        ),
        migrations.AddField(
            model_name='section',
            name='commune',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='commune'),
        ),
        migrations.AddField(
            model_name='section',
            name='condition_class',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='pavement condition class'),
        ),
        migrations.AddField(
            model_name='section',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='district_sections', to='administrations.AdminUnit'),
        ),
        migrations.AddField(
            model_name='section',
            name='end_km',
            field=models.FloatField(blank=True, null=True, verbose_name='end km'),
        ),
        migrations.AddField(
            model_name='section',
            name='lanes',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='number of lanes class'),
        ),
        migrations.AddField(
            model_name='section',
            name='length',
            field=models.FloatField(default=0.0, verbose_name='length'),
        ),
        migrations.AddField(
            model_name='section',
            name='management',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='management'),
        ),
        migrations.AddField(
            model_name='section',
            name='moisture',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='moisture class'),
        ),
        migrations.AddField(
            model_name='section',
            name='orma_way_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='orma way id'),
        ),
        migrations.AddField(
            model_name='section',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='province_sections', to='administrations.AdminUnit'),
        ),
        migrations.AddField(
            model_name='section',
            name='road_class',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='road class'),
        ),
        migrations.AddField(
            model_name='section',
            name='road_type',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='pavement type'),
        ),
        migrations.AddField(
            model_name='section',
            name='roughness',
            field=models.FloatField(blank=True, null=True, verbose_name='roughness (IRI)'),
        ),
        migrations.AddField(
            model_name='section',
            name='section_id',
            field=models.CharField(default=None, max_length=30, primary_key=True, serialize=False, verbose_name='section id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='start_km',
            field=models.FloatField(blank=True, null=True, verbose_name='start km'),
        ),
        migrations.AddField(
            model_name='section',
            name='surface_type',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='surface type'),
        ),
        migrations.AddField(
            model_name='section',
            name='temperature',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='temperature class'),
        ),
        migrations.AddField(
            model_name='section',
            name='terrain',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='terrain type'),
        ),
        migrations.AddField(
            model_name='section',
            name='traffic_growth',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='traffic annual growth scenario'),
        ),
        migrations.AddField(
            model_name='section',
            name='traffic_level',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='traffic level'),
        ),
        migrations.AddField(
            model_name='section',
            name='vpromm_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='vpromm id'),
        ),
        migrations.AddField(
            model_name='section',
            name='width',
            field=models.FloatField(blank=True, null=True, verbose_name='carriageway width'),
        ),
    ]
