# Generated by Django 2.1.4 on 2018-12-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0003_auto_20181220_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementClass',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'management class',
                'verbose_name_plural': 'management classes',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='MoistureClass',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'moisture class',
                'verbose_name_plural': 'moisture classes',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PavementConditionClass',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'pavement condition class',
                'verbose_name_plural': 'pavement condition classes',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PavementType',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'pavement type',
                'verbose_name_plural': 'pavement types',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='RoadClass',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'road class',
                'verbose_name_plural': 'road classes',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SurfaceType',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'surface type',
                'verbose_name_plural': 'surface types',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TemperatureClass',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'temperature class',
                'verbose_name_plural': 'temperature classes',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TerrainType',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'terrain type',
                'verbose_name_plural': 'terrain types',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TrafficGrowthScenario',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'traffic annual growth scenario',
                'verbose_name_plural': 'traffic annual growth scenarios',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TrafficLevel',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'traffic levels',
                'verbose_name_plural': 'traffic levels',
                'ordering': ('id',),
            },
        ),
    ]
