# Generated by Django 2.2.2 on 2019-06-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0006_auto_20190607_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaneClass',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('from_width', models.FloatField(blank=True, null=True, verbose_name='from width')),
                ('to_width', models.FloatField(blank=True, null=True, verbose_name='to width')),
                ('number_of_lanes', models.SmallIntegerField(blank=True, null=True, verbose_name='default number of lanes')),
                ('carriageway_width', models.FloatField(blank=True, null=True, verbose_name='default carriageway width')),
            ],
            options={
                'verbose_name': 'lanes class',
                'verbose_name_plural': 'lanes classes',
                'ordering': ('id',),
            },
        ),
    ]
