# Generated by Django 2.2.2 on 2019-06-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0007_laneclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficlevel',
            name='aadt_4wheel',
            field=models.FloatField(blank=True, null=True, verbose_name='aadt_4wheel'),
        ),
        migrations.AddField(
            model_name='trafficlevel',
            name='aadt_articulatedtruck',
            field=models.FloatField(blank=True, null=True, verbose_name='aadt_articulatedtruck'),
        ),
        migrations.AddField(
            model_name='trafficlevel',
            name='aadt_carmedium',
            field=models.FloatField(blank=True, null=True, verbose_name='aadt_carmedium'),
        ),
        migrations.AddField(
            model_name='trafficlevel',
            name='aadt_carsmall',
            field=models.FloatField(blank=True, null=True, verbose_name='aadt_carsmall'),
        ),
        migrations.AddField(
            model_name='trafficlevel',
            name='aadt_delivery',
            field=models.FloatField(blank=True, null=True, verbose_name='aadt_delivery'),
        ),
        migrations.AddField(
            model_name='trafficlevel',
            name='aadt_largebus',
            field=models.FloatField(blank=True, null=True, verbose_name='aadt_largebus'),
        ),
        migrations.AddField(
            model_name='trafficlevel',
            name='aadt_largetruck',
            field=models.FloatField(blank=True, null=True, verbose_name='aadt_largetruck'),
        ),
        migrations.AddField(
            model_name='trafficlevel',
            name='aadt_mediumbus',
            field=models.FloatField(blank=True, null=True, verbose_name='aadt_mediumbus'),
        ),
        migrations.AddField(
            model_name='trafficlevel',
            name='aadt_mediumtruck',
            field=models.FloatField(blank=True, null=True, verbose_name='aadt_mediumtruck'),
        ),
        migrations.AddField(
            model_name='trafficlevel',
            name='aadt_motorcyle',
            field=models.FloatField(blank=True, null=True, verbose_name='aadt_motorcyle'),
        ),
        migrations.AddField(
            model_name='trafficlevel',
            name='aadt_smallbus',
            field=models.FloatField(blank=True, null=True, verbose_name='aadt_smallbus'),
        ),
        migrations.AddField(
            model_name='trafficlevel',
            name='aadt_smalltruck',
            field=models.FloatField(blank=True, null=True, verbose_name='aadt_smalltruck'),
        ),
        migrations.AddField(
            model_name='trafficlevel',
            name='total_traffic',
            field=models.IntegerField(blank=True, null=True, verbose_name='default total traffice (veh/day)'),
        ),
    ]
